"""Generate LaTeX macros and table bodies from the experiment outputs.

Writes the % BEGIN AUTO NUMBERS ... % END AUTO NUMBERS block and the
AUTO MAIN TABLE / AUTO OOD TABLE blocks inside paper/main.tex.  Every
quantitative claim in the manuscript therefore traces back to a CSV in
results/tables/.

Re-run after any experiment script; the paper compiles even if some
experiments have not been run yet (missing values become 'n/a').
"""

from __future__ import annotations

import sys
from pathlib import Path

import numpy as np
import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from optonet.config import load_config, repo_path

TABLES = repo_path("results", "tables")
MAIN_TEX = repo_path("paper", "main.tex")
BEGIN_MARK = "% BEGIN AUTO NUMBERS"
END_MARK = "% END AUTO NUMBERS"
MODELS = ["glm", "cnn", "lstm", "transformer"]
SPLITS = ["val", "test_id", "test_ood_proto", "test_ood_freq", "test_ood_int"]


def load(name):
    p = TABLES / name
    return pd.read_csv(p) if p.exists() else None


def main() -> None:
    cfg = load_config()
    ens = load("ensemble_metrics.csv")
    stats = load("statistics.csv")
    tab = load("tabular_metrics.csv")
    uq = load("uncertainty.csv")
    tr = load("transfer.csv")
    interp = load("interpretability.csv")
    opt = load("protocol_opt.csv")
    tl = load("train_log.csv")

    lines = ["% Auto-generated by scripts/11_paper_numbers.py -- do not edit",
             "\\newcommand{\\nsource}{OptoNet simulator benchmark}"]
    defined = set()

    def macro(name, value, fmt="{:.3f}"):
        if value is None or (isinstance(value, float) and not np.isfinite(value)):
            text = "n/a"
        elif isinstance(value, str):
            text = value
        elif isinstance(value, (int, np.integer)):
            text = str(int(value))
        else:
            text = fmt.format(float(value))
        defined.add(name)
        lines.append(f"\\newcommand{{\\{name}}}{{{text}}}")

    def get(df, model, split, col, agg="mean"):
        if df is None or model not in df["model"].unique():
            return None
        m = df[(df["model"] == model) & (df["split"] == split)]
        if not len(m):
            return None
        return float(getattr(m[col], agg)())

    # dataset
    meta = repo_path("data", "meta.json")
    if meta.exists():
        import json
        d = json.loads(meta.read_text())
        macro("nTrials", d["n_trials"])
        macro("nCells", d["n_cells"])
        macro("nSpikes", d["n_spikes"])
    macro("nFamilies", len(cfg["protocols"]["train_families"]) +
          len(cfg["protocols"]["ood_families"]))
    macro("nTrainFamilies", len(cfg["protocols"]["train_families"]))
    macro("nOodFamilies", len(cfg["protocols"]["ood_families"]))
    macro("nSeeds", len(cfg["training"]["seeds"]))
    macro("conformalAlpha", cfg["uncertainty"]["conformal_alpha"])

    # per-model headline numbers
    for i, m in enumerate(MODELS):
        tag = m.capitalize()
        macro(f"Rtwo{tag}Id", get(ens, m, "test_id", "evoked_r2"))
        macro(f"auPrc{tag}Id", get(ens, m, "test_id", "bin_auprc"))
        macro(f"auRoc{tag}Id", get(ens, m, "test_id", "bin_auroc"))
        macro(f"mae{tag}Id", get(ens, m, "test_id", "evoked_mae"))
        macro(f"psth{tag}Id", get(ens, m, "test_id", "psth_r"))
        macro(f"Rtwo{tag}Proto", get(ens, m, "test_ood_proto", "evoked_r2"))
        macro(f"auPrc{tag}Proto", get(ens, m, "test_ood_proto", "bin_auprc"))
        macro(f"Rtwo{tag}Freq", get(ens, m, "test_ood_freq", "evoked_r2"))
        macro(f"Rtwo{tag}Int", get(ens, m, "test_ood_int", "evoked_r2"))
        macro(f"psth{tag}Proto", get(ens, m, "test_ood_proto", "psth_r"))
        if tl is not None and m in tl["model"].unique():
            macro(f"nParams{tag}", int(tl[tl["model"] == m]["n_params"].mean()))

    # bootstrap statistics
    for i, m in enumerate(MODELS):
        tag = m.capitalize()
        if stats is not None and ((stats["split"] == "test_id") &
                                  (stats["model"] == m)).any():
            r = stats[(stats["split"] == "test_id") & (stats["model"] == m)].iloc[0]
            macro(f"ci{tag}Lo", float(r["r2_lo"]))
            macro(f"ci{tag}Hi", float(r["r2_hi"]))
            macro(f"seedSd{tag}", float(r["r2_seed_sd"]))

    # tabular baseline
    if tab is not None:
        for name, sp in (("HgbId", "test_id"), ("HgbProto", "test_ood_proto"),
                         ("HgbFreq", "test_ood_freq"), ("HgbInt", "test_ood_int"),
                         ("HgbVal", "val")):
            m = tab[(tab["task"] == "count_evoked") & (tab["split"] == sp)]
            if len(m):
                macro(f"Rtwo{name}", float(m["r2"].mean()))
                macro(f"mae{name}", float(m["mae"].mean()))
        for name, sp in (("HgbDetId", "test_id"), ("HgbDetProto", "test_ood_proto")):
            m = tab[(tab["task"] == "detection") & (tab["split"] == sp)]
            if len(m):
                macro(f"auRoc{name}", float(m["auroc"].mean()))
                macro(f"auPrc{name}", float(m["auprc"].mean()))

    # uncertainty
    for m in MODELS:
        tag = m.capitalize()
        for split, suffix in (("test_id", "Id"), ("test_ood_proto", "Proto"),
                              ("test_ood_freq", "Freq"), ("test_ood_int", "Int")):
            cov = sd = None
            if uq is not None and ((uq["model"] == m) & (uq["split"] == split)).any():
                sel = uq[(uq["model"] == m) & (uq["split"] == split)]
                cov = float(sel["coverage"].mean())
                sd = float(sel["ensemble_std"].mean())
            macro(f"cov{tag}{suffix}", cov)
            macro(f"sd{tag}{suffix}", sd)

    # transfer (macro names must be letter-only: digits break \newcommand here)
    for cond, nm in (("oracle", "Oracle"), ("zero_shot", "ZeroShot"),
                     ("scratch_50", "ScratchN"), ("few_shot_50", "FewShotN"),
                     ("finetune_oracle_50", "FinetuneOracleN")):
        sel = tr[tr["condition"] == cond] if tr is not None else None
        macro(f"tr{nm}Rtwo", float(sel["evoked_r2"].mean()) if sel is not None and len(sel) else None)
        macro(f"tr{nm}Auprc", float(sel["bin_auprc"].mean()) if sel is not None and len(sel) else None)
    holdout = str(cfg["transfer"]["holdout_type"]).upper()
    macro("holdoutType", holdout if (tr is None or not len(tr)) else
          str(tr["holdout"].iloc[0]).upper())

    # interpretability
    for m in MODELS:
        sel = interp[interp["model"] == m] if interp is not None else None
        tag = m.capitalize()
        if sel is not None and len(sel):
            macro(f"salEnrich{tag}", float(sel["sal_enrichment"].mean()))
            macro(f"shuffleAuPrc{tag}", float(sel["shuffle_bin_auprc"].mean()),
                  fmt="{:.4f}")
            fh = float(sel["sal_first_half"].mean())
            sh = float(sel["sal_second_half"].mean())
            macro(f"salEarly{tag}", fh / sh if sh else None, fmt="{:.2f}")
        else:
            macro(f"salEnrich{tag}", None)
            macro(f"shuffleAuPrc{tag}", None, fmt="{:.4f}")
            macro(f"salEarly{tag}", None, fmt="{:.2f}")
    if interp is not None and "attn_local" in interp.columns:
        al = interp["attn_local"].dropna()
        macro("attnLocal", float(al.mean()) if len(al) else None, fmt="{:.3f}")
        ab = interp["attn_local_uniform"].dropna()
        macro("attnLocalUniform", float(ab.mean()) if len(ab) else None,
              fmt="{:.3f}")
    if interp is not None and "kernel_peak_lag_ms" in interp.columns:
        for ct in ("pc", "pv", "som"):
            sel = interp[(interp["model"] == "glm") &
                         (interp["kernel_type"] == ct)]["kernel_peak_lag_ms"].dropna()
            macro(f"glmPeak{ct.capitalize()}",
                  float(sel.mean()) if len(sel) else None, fmt="{:.0f}")

    # protocol optimisation
    for meth, nm in (("ours", "Ours"), ("constant", "Const"),
                     ("random", "Rand"), ("oracle", "Oracle")):
        sel = opt[opt["method"] == meth] if opt is not None else None
        macro(f"optErr{nm}", float(sel["abs_error"].mean()) if sel is not None and len(sel) else None)
        macro(f"optDose{nm}", float(sel["dose"].mean()) if sel is not None and len(sel) else None)
        macro(f"optWithin{nm}", float(sel["within3"].mean()) if sel is not None and len(sel) else None)
    macro("optTarget", int(opt["target"].iloc[0]) if opt is not None and len(opt) else 20)

    def ref(name, default="n/a"):
        return f"$\\{name}$" if name in defined else default

    def ci_cell(tag):
        lo, hi = f"ci{tag}Lo", f"ci{tag}Hi"
        if lo in defined and hi in defined:
            return f"$\\{lo}$--$\\{hi}$"
        return "---"

    # Table 1: in-distribution performance ---------------------------------
    rows = []
    for label, tag in (("GLM", "Glm"), ("CNN", "Cnn"), ("LSTM", "Lstm"),
                       ("OptoFormer", "Transformer")):
        rows.append(f"  {label} & {ref(f'nParams{tag}', '---')} & "
                    f"{ref(f'Rtwo{tag}Id')} ({ci_cell(tag)}) & "
                    f"{ref(f'seedSd{tag}', '---')} & {ref(f'mae{tag}Id')} & "
                    f"{ref(f'psth{tag}Id', '---')} & {ref(f'auPrc{tag}Id')} \\\\")
    rows.append(f"  HGB (trees) & --- & {ref('RtwoHgbId')} & --- & "
                f"{ref('maeHgbId', '---')} & --- & {ref('auPrcHgbId', '---')} \\\\")
    main_tab = "\n".join([
        "  \\begin{tabular}{llccccc}",
        "  \\toprule",
        "  Model & Params & $R^2$ (95\\% CI) & $\\sigma_{seed}$ & MAE & $\\rho$"
        " & Bin AUPRC \\\\",
        "  \\midrule",
        *rows,
        "  \\bottomrule",
        "  \\end{tabular}",
        "  ",
    ])

    # Table 2: evoked count R^2 across the four test regimes ---------------
    ood_rows = []
    for label, tag in (("GLM", "Glm"), ("CNN", "Cnn"), ("LSTM", "Lstm"),
                       ("OptoFormer", "Transformer")):
        ood_rows.append(f"  {label} & {ref(f'Rtwo{tag}Id')} & "
                        f"{ref(f'Rtwo{tag}Proto')} & {ref(f'Rtwo{tag}Freq')} & "
                        f"{ref(f'Rtwo{tag}Int')} \\\\")
    ood_rows.append(f"  HGB (trees) & {ref('RtwoHgbId')} & "
                    f"{ref('RtwoHgbProto', '---')} & {ref('RtwoHgbFreq', '---')} & "
                    f"{ref('RtwoHgbInt', '---')} \\\\")
    ood_tab = "\n".join([
        "  \\begin{tabular}{lcccc}",
        "  \\toprule",
        "  Model & ID & OOD protocol & OOD freq. & OOD intensity \\\\",
        "  \\midrule",
        *ood_rows,
        "  \\bottomrule",
        "  \\end{tabular}",
        "  ",
    ])

    block = "\n".join(lines) + "\n"
    tex = MAIN_TEX.read_text(encoding="utf-8")

    def replace_block(text, begin_mark, end_mark, body):
        if begin_mark in text and end_mark in text:
            head, rest = text.split(begin_mark, 1)
            _, tail = rest.split(end_mark, 1)
            return head + begin_mark + "\n" + body + end_mark + tail
        return text

    if BEGIN_MARK in tex and END_MARK in tex:
        head, rest = tex.split(BEGIN_MARK, 1)
        _, tail = rest.split(END_MARK, 1)
        tex = head + BEGIN_MARK + "\n" + block + END_MARK + tail
    else:
        tex = tex.replace("\\input{optonet_numbers}",
                          BEGIN_MARK + "\n" + block + END_MARK)
        tex = tex.replace("\\input{numbers_macros}",
                          BEGIN_MARK + "\n" + block + END_MARK)

    tex = replace_block(tex, "% BEGIN AUTO MAIN TABLE",
                        "% END AUTO MAIN TABLE", main_tab)
    tex = replace_block(tex, "% BEGIN AUTO OOD TABLE",
                        "% END AUTO OOD TABLE", ood_tab)
    MAIN_TEX.write_text(tex, encoding="utf-8")
    print(f"wrote {len(lines) - 1} macros and 2 table bodies into {MAIN_TEX}")


if __name__ == "__main__":
    main()
